name: Package Create & Publish

on:
  push:
    branches: [ master ]


  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install dependencies
        run: dotnet restore Toolkit.Localization.sln

      - name: Build
        run: dotnet build src/Toolkit.Localization/Toolkit.Localization.csproj --configuration Release --no-restore

      - name: Build the NuGet package
        run: dotnet pack src/Toolkit.Localization/Toolkit.Localization.csproj --configuration Release --output ${{env.DOTNET_ROOT}}\Package

      - name: Publish NuGet Package
        run: dotnet nuget push ${{env.DOTNET_ROOT}}\Package\*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
